CREATE TABLE IF NOT EXISTS `USER`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FIRSTNAME` varchar(255),
    `LASTNAME` varchar(255)
);
CREATE TABLE IF NOT EXISTS `ADDRESS`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CITY` varchar(255) NOT NULL ,
    `STREET` varchar(255) NOT NULL ,
    `STREETNR` varchar(255) NOT NULL ,
    `CITYCODE` varchar(255) NOT NULL 
);
CREATE TABLE IF NOT EXISTS `ORGANISATION`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` varchar(255)
);
